/// <reference path="references.ts" />

namespace TestApplication {
    export class TestApplication extends Buhta.Application {
        constructor() {
            // constructor code is auto-generated by buhta designer
            super();
            this.$$className = "TestApplication.TestApplication"

            // constructor code is auto-generated by buhta designer
        }
    }
}

// this code is auto-generated by buhta designer
Buhta.registerComponent({
    name: "Тестовое приложение",
    moduleName: "TestApplication",
    className: "TestApplication",
    inheritFrom: "",
    parent: undefined,
    description: "это тестовое приложение",
    references: ["references.ts", "testcomp2.ts"],
    createInstance: (): Buhta.DesignedComponent => new TestApplication.TestApplication()
});
// this code is auto-generated by buhta designer