/// <reference path="references.ts" />

namespace TestApplication {
    export class TestApplication extends Buhta.Application {
        constructor() {
            // constructor code is auto-generated by buhta designer
            super();
            this.$$className = "TestApplication.TestApplication"

            // constructor code is auto-generated by buhta designer
        }
    }
}

// this code is auto-generated by buhta designer
Buhta.registerComponent((comp) => {
    comp.name = "Тестовое приложение";
    comp.moduleName = "TestApplication";
    comp.className = "TestApplication";
    comp.inheritFrom = "";
    comp.parent = undefined;
    comp.description = "это тестовое приложение";
    comp.references = ["references.ts", "testcomp2.ts"];
    comp.createInstance = () => new TestApplication.TestApplication();
});

// this code is auto-generated by buhta designer