/// <reference path="../../typings/index.d.ts" />
/// <reference path="../../buhta_modules/core/dist/core.d.ts" />
/// <reference path="../../buhta_modules/components/dist/components.d.ts" />
/// <reference path="../../buhta_modules/designer/dist/designer.d.ts" />
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
/// <reference path="references.ts" />
var TestModule;
(function (TestModule) {
    var TestComp2 = (function (_super) {
        __extends(TestComp2, _super);
        function TestComp2() {
            // constructor code is auto-generated by buhta designer
            _super.call(this);
            this.name = "Тестовый компонент 2222222222";
            this.sqlname = undefined;
            this.проблема = undefined;
            // constructor code is auto-generated by buhta designer
        }
        return TestComp2;
    }(Buhta.DesignedComponent));
    TestModule.TestComp2 = TestComp2;
})(TestModule || (TestModule = {}));
/// <reference path="references.ts" />
/// <reference path="testcomp2.ts" />
var TestModule;
(function (TestModule) {
    var Org = (function (_super) {
        __extends(Org, _super);
        function Org() {
            // constructor code is auto-generated by buhta designer
            _super.call(this);
            this.$$className = "TestModule.Org";
            this.sqlName = "Организация";
            this.addColumn(function (column) {
                column.name = "Номер";
            });
            this.addColumn(function (column) {
                column.name = "Название";
            });
            this.addColumn(function (column) {
                column.name = "Город";
            });
            // constructor code is auto-generated by buhta designer
        }
        return Org;
    }(Buhta.Table));
    TestModule.Org = Org;
})(TestModule || (TestModule = {}));
// this code is auto-generated by buhta designer
Buhta.registerComponent({
    name: "Организация",
    className: "Org",
    moduleName: "TestModule",
    inheritFrom: "Buhta.Table",
    parent: "TestModule.TestModule",
    description: "это тестовый компонент таблицы Организация",
    references: ["references.ts", "testcomp2.ts"],
    createInstance: function () { return new TestModule.Org(); }
});
// this code is auto-generated by buhta designer 
/// <reference path="references.ts" />
/// <reference path="testcomp2.ts" />
var TestModule;
(function (TestModule) {
    var TestComp1 = (function (_super) {
        __extends(TestComp1, _super);
        function TestComp1() {
            // constructor code is auto-generated by buhta designer
            _super.call(this);
            this.$$className = "TestModule.TestComp1";
            this.name = "Тестовый компонент 12rrr";
            this.sqlname = undefined;
            this.проблема = undefined;
            // constructor code is auto-generated by buhta designer
        }
        return TestComp1;
    }(TestModule.TestComp2));
    TestModule.TestComp1 = TestComp1;
})(TestModule || (TestModule = {}));
// this code is auto-generated by buhta designer
Buhta.registerComponent({
    name: "Тестовый компонент 1278",
    className: "TestComp1",
    moduleName: "TestModule",
    inheritFrom: "TestComp2",
    parent: "TestModule.TestModule",
    description: "это тестовый компонент",
    references: ["references.ts", "testcomp2.ts"],
    createInstance: function () { return new TestModule.TestComp1(); }
});
// this code is auto-generated by buhta designer 
/// <reference path="references.ts" />
/// <reference path="testcomp2.ts" />
var TestModule;
(function (TestModule_1) {
    var TestModule = (function (_super) {
        __extends(TestModule, _super);
        function TestModule() {
            // constructor code is auto-generated by buhta designer
            _super.call(this);
            this.$$className = "TestModule.TestModule";
            // constructor code is auto-generated by buhta designer
        }
        return TestModule;
    }(Buhta.Module));
    TestModule_1.TestModule = TestModule;
})(TestModule || (TestModule = {}));
// this code is auto-generated by buhta designer
Buhta.registerComponent({
    name: "тестовый модуль 1",
    moduleName: "TestModule",
    className: "TestModule",
    inheritFrom: "Buhta.Module",
    parent: "TestApplication.TestApplication",
    description: "это тестовый модуль",
    references: ["references.ts", "testcomp2.ts"],
    createInstance: function () { return new TestModule.TestModule(); }
});
// this code is auto-generated by buhta designer 
//# sourceMappingURL=testmodule.js.map