/// <reference path="references.ts" />
/// <reference path="testcomp2.ts" />
namespace TestModule {
    export class Org extends Buhta.Table {
        constructor() {
            // constructor code is auto-generated by buhta designer
            super();
            this.$$className = "TestModule.Org"
            this.sqlName = "Организацияj";
            this.addColumn((column) => {
                column.name = "Номер";
            });

            this.addColumn((column) => {
                column.name = "Название";
            });

            this.addColumn((column) => {
                column.name = "Город";
            });

            // constructor code is auto-generated by buhta designer
        }
    }
}

// this code is auto-generated by buhta designer
Buhta.componentRegistry["TestModule.Org"] = {
    name: "Организация",
    className: "Org",
    moduleName: "TestModule",
    inheritFrom: "Buhta.Table",
    description: "это тестовый компонент таблицы Организация",
    parent: "TestModule.TestModule",
    references: ["references.ts", "testcomp2.ts"],
    createInstance: (): Buhta.DesignedComponent => new TestModule.Org()
};
// this code is auto-generated by buhta designer