/// <reference path="references.ts" />
namespace TestModule {
    export class TestComp2 extends Buhta.DesignedComponent {
        constructor() {
            // constructor code is auto-generated by buhta designer
            super();
            this.name = "Тестовый компонент 2222222222";
            this.sqlname = undefined;
            this.проблема = undefined;
            // constructor code is auto-generated by buhta designer
        }
        name: string;
        sqlname: string;
        проблема: string;

    }
}
