/// <reference path="references.ts" />
/// <reference path="testcomp2.ts" />
namespace TestModule {
    export class TestComp1 extends TestComp2 {
        constructor() {
            // constructor code is auto-generated by buhta designer
            super();
            this.$$className = "TestModule.TestComp1"
            this.name = "Тестовый компонент 12rrr";
            this.sqlname = undefined;
            this.проблема = undefined;
            // constructor code is auto-generated by buhta designer
        }
    }
}

// this code is auto-generated by buhta designer
Buhta.registerComponent({
    name: "Тестовый компонент 1278",
    className: "TestComp1",
    moduleName: "TestModule",
    inheritFrom: "TestComp2",
    parent: "TestModule.TestModule",
    description: "это тестовый компонент",
    references: ["references.ts", "testcomp2.ts"],
    createInstance: (): Buhta.DesignedComponent => new TestModule.TestComp1()
});
// this code is auto-generated by buhta designer