/// <reference path="references.ts" />
/// <reference path="testcomp2.ts" />
namespace TestModule {
    export class TestModule extends Buhta.Module {
        constructor() {
            // constructor code is auto-generated by buhta designer
            super();
            this.$$className = "TestModule.TestModule"

            // constructor code is auto-generated by buhta designer
        }
    }
}

// this code is auto-generated by buhta designer
Buhta.registerComponent({
    name: "тестовый модуль 1",
    moduleName: "TestModule",
    className: "TestModule",
    inheritFrom: "Buhta.Module",
    parent: "TestApplication.TestApplication",
    description: "это тестовый модуль",
    references: ["references.ts", "testcomp2.ts"],
    createInstance: (): Buhta.DesignedComponent => new TestModule.TestModule()
});
// this code is auto-generated by buhta designer