/// <reference path="references.ts" />
/// <reference path="testcomp2.ts" />
namespace TestModule {
    export class TestComp1 extends TestComp2 {
        constructor() {
            // constructor code is auto-generated by buhta designer
            super();
            this.$$className = "TestModule.TestComp1"
            this.name = "Тестовый компонент 12rrr";
            this.sqlname = undefined;
            this.проблема = undefined;
            // constructor code is auto-generated by buhta designer
        }
    }
}

// this code is auto-generated by buhta designer
Buhta.registerComponent((comp) => {
    comp.name = "Тестовый компонент 1278";
    comp.moduleName = "TestModule";
    comp.className = "TestComp1";
    comp.inheritFrom = "TestComp2";
    comp.parent = "TestModule.TestModule";
    comp.description = "это тестовый компонент";
    comp.references = ["references.ts", "testcomp2.ts"];
    comp.createInstance = () => new TestModule.TestComp1();
});
// this code is auto-generated by buhta designer